from . import permit

class Permit( permit.Permit ):
    name = 'aries'
    rules = (( lambda u: u.anonymous,
               (( 'addgroup', 'anonymous' )),
               (( 'rmgroup',  'anonymous' ),
                ( 'addgroup', 'authenticated' ))),)
    data = (
        ( '0.0.1',
          ( '#groups',
            ( 'anonymous', dict( title='Anonymous Users' )),
            ( 'authenticated', dict( title='Authenticated Users' )),
            ( 'confirmed', dict( title='Confirmed Users' )),
            ( 'verified', dict( title='Verified Users' )),
            ( 'power', dict( title='Power-Users' )),
            ( 'staff', dict(
                title='Internal Staff',
                is_staff=True
            ),
              ( '#permissions',
                ( 'add change delete',
                  ( 'user', dict( ct='users' )),
                  ( 'group', dict( ct='groups' )),
                  ( 'role', dict( ct='roles' )),
                  ( 'policy', dict( ct='policies' )),
                  ( 'permission', dict( ct='permissions' )),
                ))),
            ( 'admin', dict(
                title='Admin Staff',
                is_superuser=True
            )),
          ),
          ( '#roles',
            ( 'manager',
              ( 'user', dict( title='User Manager' ),
                ( '#permissions',
                  ( 'add change delete',
                    ( 'group role',
                      ( 'user', dict( ct='users' ))),
                  ))),
              ( 'security', dict( title='Security Manager' ),
                ( '#permissions',
                  ( 'add change delete',
                    ( 'user', dict( ct='users' )),
                    ( 'group', dict( ct='groups' )),
                    ( 'role', dict( ct='roles' )),
                    ( 'policy', dict( ct='policies' )),
                    ( 'permission', dict( ct='permissions' )),
                    ( 'permissions',
                      ( 'user', dict( ct='users' )),
                      ( 'group', dict( ct='groups' )),
                      ( 'role', dict( ct='roles' )),
                      ( 'policy', dict( ct='policies' )),
                    ),
                    ( 'policy',
                      ( 'user', dict( ct='users' )),
                      ( 'group', dict( ct='groups' )),
                      ( 'role', dict( ct='roles' )),
                    ),
                    ( 'role',
                      ( 'user', dict( ct='users' )),
                      ( 'group', dict( ct='groups' )),
                    ),
                    ( 'group',
                      ( 'user', dict( ct='users' )),
                    ),
                  ))),
            )),
          ( '#permissions', ),
          ( '#policies', ),
          ( '#users',
            ( 'system', dict(
                title="System User",
                is_superuser=True,
                is_staff=True
            ))),
        ),
    )
