# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 23:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('installed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name_plural': 'registries'},
        ),
        migrations.AddField(
            model_name='action',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_friede_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='auto_install',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='auto_user_install',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='min_version',
            field=models.CharField(default='0.0.0', max_length=32),
        ),
        migrations.AddField(
            model_name='app',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='user_installable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='app',
            name='user_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_friede_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registry',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_friede_registries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_registries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setting',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_friede_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userapp',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use', to='friede.App'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friede_apps_use', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='friede_apps', through='friede.UserApp', to=settings.AUTH_USER_MODEL),
        ),
    ]
