# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-23 05:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friede', '0002_auto_20190613_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_action_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_action_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='app',
            name='rest',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='link',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_link_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_link_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registry',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_registry_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_registry_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_setting_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friede_setting_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
