# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friede', '0003_auto_20190623_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='action',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='action',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='link',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='owner',
        ),
        migrations.AddField(
            model_name='userapp',
            name='version',
            field=models.CharField(default='0.0.0', max_length=32),
        ),
    ]
