# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friede', '0004_auto_20190714_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='actionentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blockentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='containerentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iconentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='linkentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referenceentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='screenentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='settingentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shellentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='slotentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='themeentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='widgetentry',
            name='name',
            field=models.SlugField(max_length=255),
        ),
    ]
