# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-28 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friede', '0005_auto_20190726_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='app',
        ),
        migrations.AddField(
            model_name='action',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_actions', to='friede.App'),
        ),
        migrations.AddField(
            model_name='icon',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_icons', to='friede.App'),
        ),
        migrations.AddField(
            model_name='link',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_links', to='friede.App'),
        ),
        migrations.AddField(
            model_name='reference',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_references', to='friede.App'),
        ),
        migrations.AddField(
            model_name='registry',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_registries', to='friede.App'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='friede.App'),
        ),
        migrations.AlterField(
            model_name='location',
            name='registry_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='_location', serialize=False, to='friede.Registry'),
        ),
    ]
