# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-02 02:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friede', '0006_auto_20190728_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('goodness', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='friede.ActionStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('by', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothetical', models.BooleanField(default=True)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('ops', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None)),
                ('done', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='friede.Action')),
                ('conflicts', models.ManyToManyField(related_name='_operation_conflicts_+', to='friede.Operation')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='friede.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='OpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='friede.Operation')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='friede.OpStatus')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='friede.ActionStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255)),
                ('type', models.SlugField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='friede.Operation')),
            ],
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='friede.OpStatus'),
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friede_operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
