# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friede', '0008_auto_20200207_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opstatus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='friede.OpStatus'),
        ),
    ]
