# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-08 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('friede', '0009_auto_20200207_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsement',
            name='by',
        ),
        migrations.AddField(
            model_name='endorsement',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='by_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endorsement',
            name='by_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='endorses', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endorsement',
            name='committed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='hash',
            field=models.CharField(default='{}', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_by', to='contenttypes.ContentType'),
        ),
    ]
