# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-17 22:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0006_auto_20190714_1823'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intrepid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.AddField(
            model_name='capacity',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='intrepid_capacities', to='aries.Permission'),
        ),
        migrations.AddField(
            model_name='position',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intrepid_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='system',
            field=models.ManyToManyField(blank=True, related_name='intrepid_roles', to='aries.Role'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='intrepid_teams', through='intrepid.Position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='opened',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='opened',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='intended_own',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='follows',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedes', to='intrepid.Budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='intended_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='intended_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='intended_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='external',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='external',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='intended_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='intended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='intended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='phases', to='intrepid.Target'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='plans', to='intrepid.Target'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='strategies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='intrepid.Strategy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='projects', to='intrepid.Target'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='intended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='intended_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='intrepid.Position'),
        ),
        migrations.AlterField(
            model_name='service',
            name='intended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='steps', to='intrepid.Target'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='strategies', to='intrepid.Target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='intended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='hierarchichal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
