# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from .models import *

admin.site.register( Note )
admin.site.register( Resource )
admin.site.register( Product )
admin.site.register( Goal )
admin.site.register( Objective )
admin.site.register( Target )
admin.site.register( Strategy )
admin.site.register( Plan )
admin.site.register( Phase )
admin.site.register( Step )
admin.site.register( Project )
admin.site.register( Task )
admin.site.register( Action )
admin.site.register( Currency )
admin.site.register( Account )
admin.site.register( Pool )
admin.site.register( Allotment )
admin.site.register( Allocation )
admin.site.register( Income )
admin.site.register( Expense )
admin.site.register( External )
admin.site.register( Sink )
admin.site.register( Asset )
admin.site.register( Donation )
admin.site.register( Service )
admin.site.register( Rental )
admin.site.register( Source )
admin.site.register( Liability )
admin.site.register( Contribution )
admin.site.register( Commission )
admin.site.register( Employment )
admin.site.register( Investment )
admin.site.register( Receipt )
admin.site.register( Deposit )
admin.site.register( Payment )
admin.site.register( Budget )
admin.site.register( Line )
admin.site.register( Transfer )
admin.site.register( Relocation )
admin.site.register( Earning )
admin.site.register( Purchase )
admin.site.register( Team )
admin.site.register( Position )
admin.site.register( Role )
admin.site.register( Responsibility )
admin.site.register( Capacity )
admin.site.register( User )
admin.site.register( Taxonomy )
admin.site.register( Term )
