from django.conf.urls import url
from rest_framework import routers
from . import views

app_name = 'intrepid'
router = routers.DefaultRouter()
router.register( r'notes',            NoteViewSet           )
router.register( r'resourcse',        ResourceViewSet       )
router.register( r'products',         ProductViewSet        )
router.register( r'goals',            GoalViewSet           )
router.register( r'objectives',       ObjectiveViewSet      )
router.register( r'targets',          TargetViewSet         )
router.register( r'strategies',       StrategyViewSet       )
router.register( r'plans',            PlanViewSet           )
router.register( r'phases',           PhaseViewSet          )
router.register( r'steps',            StepViewSet           )
router.register( r'projects',         ProjectViewSet        )
router.register( r'tasks',            TaskViewSet           )
router.register( r'actions',          ActionViewSet         )
router.register( r'currencies',       CurrencyViewSet       )
router.register( r'accounts',         AccountViewSet        )
router.register( r'pools',            PoolViewSet           )
router.register( r'allotments',       AllotmentViewSet      )
router.register( r'allocations',      AllocationViewSet     )
router.register( r'incomes',          IncomeViewSet         )
router.register( r'expenses',         ExpenseViewSet        )
router.register( r'assets',           AssetViewSet          )
router.register( r'donations',        DonationViewSet       )
router.register( r'services',         ServiceViewSet        )
router.register( r'rentals',          RentalViewSet         )
router.register( r'sources',          SourceViewSet         )
router.register( r'liabilities',      LiabilityViewSet      )
router.register( r'contributions',    ContributionViewSet   )
router.register( r'commissions',      CommissionViewSet     )
router.register( r'employments',      EmploymentViewSet     )
router.register( r'investments',      InvestmentViewSet     )
router.register( r'receipts',         ReceiptViewSet        )
router.register( r'deposits',         DepositViewSet        )
router.register( r'payments',         PaymentViewSet        )
router.register( r'budgets',          BudgetViewSet         )
router.register( r'lines',            LineViewSet           )
router.register( r'transfers',        TransferViewSet       )
router.register( r'relocations',      RelocationViewSet     )
router.register( r'earnings',         EarningViewSet        )
router.register( r'purchases',        PurchaseViewSet       )
router.register( r'teams',            TeamViewSet           )
router.register( r'positions',        PositionViewSet       )
router.register( r'roles',            RoleViewSet           )
router.register( r'responsibilities', ResponsibilityViewSet )
router.register( r'capacities',       CapacityViewSet       )
router.register( r'users',            UserViewSet           )
router.register( r'taxonomies',       TaxonomyViewSet       )
router.register( r'terms',            TermViewSet           )

urlpatterns = [
    url( r'^$', views.index, name='index' ),

]
