from django.conf.urls import url
from rest_framework import routers
from . import views

app_name = 'intrepid'
router = routers.DefaultRouter()
router.register( r'notes',            views.NoteViewSet           )
router.register( r'resourcse',        views.ResourceViewSet       )
router.register( r'products',         views.ProductViewSet        )
router.register( r'goals',            views.GoalViewSet           )
router.register( r'objectives',       views.ObjectiveViewSet      )
router.register( r'targets',          views.TargetViewSet         )
router.register( r'strategies',       views.StrategyViewSet       )
router.register( r'plans',            views.PlanViewSet           )
router.register( r'phases',           views.PhaseViewSet          )
router.register( r'steps',            views.StepViewSet           )
router.register( r'projects',         views.ProjectViewSet        )
router.register( r'tasks',            views.TaskViewSet           )
router.register( r'actions',          views.ActionViewSet         )
router.register( r'currencies',       views.CurrencyViewSet       )
router.register( r'accounts',         views.AccountViewSet        )
router.register( r'pools',            views.PoolViewSet           )
router.register( r'allotments',       views.AllotmentViewSet      )
router.register( r'allocations',      views.AllocationViewSet     )
router.register( r'incomes',          views.IncomeViewSet         )
router.register( r'expenses',         views.ExpenseViewSet        )
router.register( r'assets',           views.AssetViewSet          )
router.register( r'donations',        views.DonationViewSet       )
router.register( r'services',         views.ServiceViewSet        )
router.register( r'rentals',          views.RentalViewSet         )
router.register( r'sources',          views.SourceViewSet         )
router.register( r'liabilities',      views.LiabilityViewSet      )
router.register( r'contributions',    views.ContributionViewSet   )
router.register( r'commissions',      views.CommissionViewSet     )
router.register( r'employments',      views.EmploymentViewSet     )
router.register( r'investments',      views.InvestmentViewSet     )
router.register( r'receipts',         views.ReceiptViewSet        )
router.register( r'deposits',         views.DepositViewSet        )
router.register( r'payments',         views.PaymentViewSet        )
router.register( r'budgets',          views.BudgetViewSet         )
router.register( r'lines',            views.LineViewSet           )
router.register( r'transfers',        views.TransferViewSet       )
router.register( r'relocations',      views.RelocationViewSet     )
router.register( r'earnings',         views.EarningViewSet        )
router.register( r'purchases',        views.PurchaseViewSet       )
router.register( r'teams',            views.TeamViewSet           )
router.register( r'positions',        views.PositionViewSet       )
router.register( r'roles',            views.RoleViewSet           )
router.register( r'responsibilities', views.ResponsibilityViewSet )
router.register( r'capacities',       views.CapacityViewSet       )
router.register( r'users',            views.UserViewSet           )
router.register( r'taxonomies',       views.TaxonomyViewSet       )
router.register( r'terms',            views.TermViewSet           )

urlpatterns = [
    url( r'^$', views.index, name='index' ),

]
