<template lang="html">
  <font-awesome-icon v-if="isFontAwesome" :class=classes :icon=iconName />
  <i v-else :icon=iconName :class=classes />
</template>

<script lang="js">
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faBed,
  faBookmark,
  faBorderNone,
  faBoxOpen,
  faBullseye,
  faCalendarAlt,
  faCartArrowDown,
  faChartLine,
  faChessKnight,
  faCog,
  faCoins,
  faColumns,
  faCompress,
  faCreditCard,
  faCrosshairs,
  faCube,
  faDesktop,
  faDollarSign,
  faDollyFlatbed,
  faDonate,
  faDownload,
  faDraftingCompass,
  faEdit,
  faExchangeAlt,
  faExpand,
  faExternalLinkAlt,
  faEye,
  faFileAlt,
  faFileCode,
  faFileContract,
  faFileSignature,
  faFileUpload,
  faFireAlt,
  faFolderMinus,
  faFolderPlus,
  faGem,
  faHandHoldingUsd,
  faHome,
  faImage,
  faIndent,
  faKey,
  faLevelDownAlt,
  faLevelUpAlt,
  faLink,
  faList,
  faLocationArrow,
  faMobileAlt,
  faMoneyBillWave,
  faMoneyCheck,
  faMoneyCheckAlt,
  faNewspaper,
  faObjectGroup,
  faParagraph,
  faPhone,
  faPiggyBank,
  faPlug,
  faPlus,
  faProjectDiagram,
  faReceipt,
  faRedoAlt,
  faRocket,
  faRss,
  faShoePrints,
  faSignInAlt,
  faSignOutAlt,
  faSitemap,
  faStickyNote,
  faStoreAlt,
  faSyncAlt,
  faTabletAlt,
  faTag,
  faTags,
  faTasks,
  faTaxi,
  faTerminal,
  faToggleOff,
  faToggleOn,
  faTractor,
  faTrademark,
  faTrash,
  faTrophy,
  faTruckMoving,
  faUndoAlt,
  faUser,
  faUserCheck,
  faUserCog,
  faUserGraduate,
  faUserMd,
  faUserNinja,
  faUserNurse,
  faUsers,
  faUserTag,
  faUserTie,
  faUserTimes,
  faWalking,
  faWallet,
  faWarehouse,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faBed,
  faBookmark,
  faBorderNone,
  faBoxOpen,
  faBullseye,
  faCalendarAlt,
  faCartArrowDown,
  faChartLine,
  faChessKnight,
  faCog,
  faCoins,
  faColumns,
  faCompress,
  faCreditCard,
  faCrosshairs,
  faCube,
  faDesktop,
  faDollarSign,
  faDollyFlatbed,
  faDonate,
  faDownload,
  faDraftingCompass,
  faEdit,
  faExchangeAlt,
  faExpand,
  faExternalLinkAlt,
  faEye,
  faFileAlt,
  faFileCode,
  faFileContract,
  faFileSignature,
  faFileUpload,
  faFireAlt,
  faFolderMinus,
  faFolderPlus,
  faGem,
  faHandHoldingUsd,
  faHome,
  faImage,
  faIndent,
  faKey,
  faLevelDownAlt,
  faLevelUpAlt,
  faLink,
  faList,
  faLocationArrow,
  faMobileAlt,
  faMoneyBillWave,
  faMoneyCheck,
  faMoneyCheckAlt,
  faNewspaper,
  faObjectGroup,
  faParagraph,
  faPhone,
  faPiggyBank,
  faPlug,
  faPlus,
  faProjectDiagram,
  faReceipt,
  faRedoAlt,
  faRocket,
  faRss,
  faShoePrints,
  faSignInAlt,
  faSignOutAlt,
  faSitemap,
  faStickyNote,
  faStoreAlt,
  faSyncAlt,
  faTabletAlt,
  faTag,
  faTags,
  faTasks,
  faTaxi,
  faTerminal,
  faToggleOff,
  faToggleOn,
  faTractor,
  faTrademark,
  faTrash,
  faTrophy,
  faTruckMoving,
  faUndoAlt,
  faUser,
  faUserCheck,
  faUserCog,
  faUserGraduate,
  faUserMd,
  faUserNinja,
  faUserNurse,
  faUsers,
  faUserTag,
  faUserTie,
  faUserTimes,
  faWalking,
  faWallet,
  faWarehouse,
);

export default {
  name: 'MfIcon',
  mixins: [],
  components: { FontAwesomeIcon },
  props: {
    icon: {
      type: String,
      required: true
    },
    mode: {
      type: String,
      default: 'prefix'
    }
  },
  data() {
    return {
    };
  },
  created() {},
  mounted() {},
  methods: {},
  computed: {
    iconLibrary() {
      return this.icon.split('.')[0]
    },
    iconName() {
      return this.icon.split('.')[1]
    },
    isFontAwesome() {
      return this.iconLibrary === 'fontawesome'
    },
    classes() {
      return [ 'mf-icon', 'mf-icon-' + this.mode ]
    }
  }
}
</script>

<style lang="scss">
.mf-icon {
  &-bg {
    position: absolute;
    top: -2px;
    lift: -2px;
    font-size: 72px;
    color: rgba(0,0,0,0.05);
  } 
}
</style>
