# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-21 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0003_auto_20190621_0131'),
    ]

    operations = [
    ]
