# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-21 01:31
from __future__ import unicode_literals

from django.db import migrations

def create_types( apps, schema_editor ):
    db_alias = schema_editor.connection.alias
    AuthPerm = apps.get_model( 'auth', 'Permission' )
    Permission = apps.get_model( 'aries', 'Permission' )
    AuthGroup = apps.get_model( 'auth', 'Group' )
    Group = apps.get_model( 'aries', 'Group' )
    for p in AuthPerm.objects.all():
        try:
            Permission.objects.get( pk=p.pk )
        except Permission.DoesNotExist:
            Permission.objects\
                      .using( db_alias )\
                      .create( auth_ptr=p )\
                      .save_base( raw=True )
            print 'attached permission', p.name
    for g in AuthGroup.objects.all():
        try:
            Group.objects.get( pk=p.pk )
        except Group.DoesNotExist:
            Group.objects\
                 .using( db_alias )\
                 .create( auth_ptr=p, title=g.name.title().replace( '_', ' ' ))\
                 .save_base( raw=True )
            print 'attached group', g.name

class Migration( migrations.Migration ):

    dependencies = [
        ( 'aries', '0003_auto_20190621_0131' ),
    ]

    operations = [
        migrations.RunPython( create_types, migrations.RunPython.noop )
    ]
