# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-21 01:31
from __future__ import unicode_literals

from django.db import migrations

def create_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    AuthPerms = apps.get_model( 'auth', 'Permission' )
    Permission = apps.get_model( 'aries', 'Permission' )
    for p in AuthPerms.objects.all():
        try:
            Permission.objects.get( pk=p.pk )
        except Permission.DoesNotExist:
            p0 = Permission.objects.using( db_alias ).create( auth_ptr=p )
            p0.save_base( raw=True )
            print 'attached', p.name

class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0003_auto_20190621_0131'),
    ]

    operations = [
        migrations.RunPython( create_types, migrations.RunPython.noop )
    ]
