# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-06 18:43
from __future__ import unicode_literals

import aries.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aries', '0006_auto_20190714_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('received', models.DateTimeField(blank=True, null=True)),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(default=aries.models._getsystemuser, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='edit', max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='edit', max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('mutual', 'Mutual'), ('unconfirmed', 'Unconfirmed'), ('disputed', 'Disputed'), ('denied', 'Denied')], default='unconfirmed', max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('initiated', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knows', to=settings.AUTH_USER_MODEL)),
                ('rsvp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='aries.UserConnection')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('reverse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aries.UserConnectionType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('base_id', models.PositiveIntegerField()),
                ('view_id', models.PositiveIntegerField()),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aries_view_bases', to='contenttypes.ContentType')),
                ('view_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aries_views', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='manager_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='manager_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='userconnection',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aries.UserConnectionType'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='aries.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together=set([('first', 'second', 'type')]),
        ),
    ]
