# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0007_auto_20191006_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='connection',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='aries.UserConnection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
