# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0009_auto_20191031_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnectiontype',
            name='reverse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='aries.UserConnectionType'),
        ),
    ]
